import { Course } from '@/types/course';
import { Lesson } from '@/types/lesson';
import { UserProfile, Achievement } from '@/types/user';
import { LeaderboardData } from '@/types/leaderboard';

export const MOCK_USER: UserProfile = {
  id: 'usr_101',
  username: 'learner',
  displayName: 'learner',
  avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=learner&backgroundColor=b6e3f4',
  avatarId: 'avatar_01',
  streak: 5,
  longestStreak: 5,
  xp: 120,
  hearts: 5,
  maxHearts: 5,
  gems: 100,
  completedSkills: 6,
  totalSkills: 18,
  dailyGoal: 50,
  dailyGoalProgress: 10,
  league: 'Gold League',
  leagueRank: 4,
  joinedDate: 'Joined October 2024',
};

export const MOCK_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach_1',
    title: 'Wildfire',
    description: 'Reach a 7-day streak',
    icon: '🔥',
    progress: 5,
    maxProgress: 7,
    unlocked: false,
    rewardGems: 50,
    level: 1,
    color: '#ff9600',
  },
  {
    id: 'ach_2',
    title: 'Sage',
    description: 'Earn 1000 XP',
    icon: '📚',
    progress: 120,
    maxProgress: 1000,
    unlocked: false,
    rewardGems: 100,
    level: 2,
    color: '#1cb0f6',
  },
  {
    id: 'ach_3',
    title: 'Scholar',
    description: 'Learn 50 new words',
    icon: '🎓',
    progress: 24,
    maxProgress: 50,
    unlocked: false,
    rewardGems: 75,
    level: 1,
    color: '#ce82ff',
  },
];

export const MOCK_LEADERBOARD: LeaderboardData = {
  league: 'Amethyst League',
  timeRemainingDays: 3,
  entries: [
    { id: 'usr_2', rank: 1, username: 'Orion', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Orion&backgroundColor=ffd5dc', xp: 1250, streak: 14, isCurrentUser: false },
    { id: 'usr_3', rank: 2, username: 'Sarah', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah&backgroundColor=c0aede', xp: 980, streak: 9, isCurrentUser: false },
    { id: 'usr_4', rank: 3, username: 'Rahul', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rahul&backgroundColor=d1d4f9', xp: 750, streak: 6, isCurrentUser: false },
    { id: 'usr_101', rank: 4, username: 'learner', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=learner&backgroundColor=b6e3f4', xp: 120, streak: 5, isCurrentUser: true },
    { id: 'usr_5', rank: 5, username: 'Elena', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elena&backgroundColor=ffdfbf', xp: 90, streak: 3, isCurrentUser: false },
    { id: 'usr_6', rank: 6, username: 'David', avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David&backgroundColor=c0aede', xp: 45, streak: 1, isCurrentUser: false },
  ],
};

export const MOCK_COURSE: Course = {
  id: 1,
  name: 'Spanish Course',
  code: 'es',
  flag: '🇪🇸',
  units: [
    {
      id: 1,
      number: 1,
      title: 'Unit 1: Basics & Essentials',
      description: 'Form basic sentences, greet people, and order food',
      color: 'bg-[#58cc02]',
      skills: [
        {
          id: 'sk_greetings',
          title: 'Greetings',
          description: 'Say hello and ask how people are doing',
          icon: 'MessageSquare',
          status: 'COMPLETED',
          totalLessons: 3,
          completedLessons: 3,
          crowns: 3,
          maxCrowns: 3,
          positionOffset: 0,
        },
        {
          id: 'sk_introductions',
          title: 'Introductions',
          description: 'Introduce yourself and ask names',
          icon: 'UserCheck',
          status: 'COMPLETED',
          totalLessons: 4,
          completedLessons: 4,
          crowns: 3,
          maxCrowns: 3,
          positionOffset: 45,
        },
        {
          id: 'sk_phrases',
          title: 'Key Phrases',
          description: 'Essential polite phrases and responses',
          icon: 'Smile',
          status: 'COMPLETED',
          totalLessons: 4,
          completedLessons: 4,
          crowns: 3,
          maxCrowns: 3,
          positionOffset: 80,
        },
        {
          id: 'sk_food',
          title: 'Food & Drinks',
          description: 'Order food, coffee, and ask for the bill',
          icon: 'Utensils',
          status: 'CURRENT',
          totalLessons: 4,
          completedLessons: 2,
          crowns: 1,
          maxCrowns: 3,
          positionOffset: 80,
        },
        {
          id: 'sk_family',
          title: 'Family',
          description: 'Talk about your family members and pets',
          icon: 'Users',
          status: 'AVAILABLE',
          totalLessons: 5,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 45,
        },
        {
          id: 'sk_animals',
          title: 'Animals & Pets',
          description: 'Describe dogs, cats, and birds',
          icon: 'Compass',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: -45,
        },
        {
          id: 'sk_travel',
          title: 'Travel & Taxi',
          description: 'Ask for directions and buy train tickets',
          icon: 'Compass',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: -80,
        },
        {
          id: 'sk_numbers',
          title: 'Numbers 1-100',
          description: 'Count items and state prices',
          icon: 'Book',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: -45,
        },
      ],
    },
    {
      id: 2,
      number: 2,
      title: 'Unit 2: Daily Life & Routines',
      description: 'Describe daily activities, shopping, and dining',
      color: 'bg-[#ff9600]',
      skills: [
        {
          id: 'sk_shopping',
          title: 'Shopping',
          description: 'Ask prices and buy clothes',
          icon: 'ShoppingBag',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 0,
        },
        {
          id: 'sk_hobbies',
          title: 'Hobbies',
          description: 'Express what sports and activities you like',
          icon: 'Smile',
          status: 'LOCKED',
          totalLessons: 5,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 50,
        },
        {
          id: 'sk_home',
          title: 'My House',
          description: 'Describe furniture and rooms',
          icon: 'Home',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 85,
        },
        {
          id: 'sk_work',
          title: 'Jobs & Work',
          description: 'Talk about professions and office life',
          icon: 'UserCheck',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 85,
        },
        {
          id: 'sk_restaurant',
          title: 'Restaurant',
          description: 'Reserve tables and request special diets',
          icon: 'Utensils',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 50,
        },
        {
          id: 'sk_routine',
          title: 'Morning Routine',
          description: 'Describe getting up, showering, and breakfast',
          icon: 'Home',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: -50,
        },
        {
          id: 'sk_time',
          title: 'Time & Dates',
          description: 'Tell time, days of week, and months',
          icon: 'Book',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: -85,
        },
      ],
    },
    {
      id: 3,
      number: 3,
      title: 'Unit 3: Places & Navigation',
      description: 'Navigate cities, book hotels, and discuss weather',
      color: 'bg-[#1cb0f6]',
      skills: [
        {
          id: 'sk_directions',
          title: 'Directions',
          description: 'Find museums, parks, and bus stops',
          icon: 'Compass',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 0,
        },
        {
          id: 'sk_hotel',
          title: 'Hotel Booking',
          description: 'Check in, request extra towels, and key cards',
          icon: 'Home',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 45,
        },
        {
          id: 'sk_weather',
          title: 'Weather',
          description: 'Talk about rain, sunshine, and temperatures',
          icon: 'Smile',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 75,
        },
        {
          id: 'sk_feelings',
          title: 'Feelings & Health',
          description: 'Express happiness, tiredness, and doctor visits',
          icon: 'Smile',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 75,
        },
        {
          id: 'sk_city',
          title: 'City Transport',
          description: 'Subway, bus lines, and airport terminals',
          icon: 'Compass',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 45,
        },
        {
          id: 'sk_emergencies',
          title: 'Emergencies',
          description: 'Ask for help and report lost items',
          icon: 'MessageSquare',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: -45,
        },
        {
          id: 'sk_sightseeing',
          title: 'Sightseeing',
          description: 'Visit monuments, tickets, and souvenir stores',
          icon: 'ShoppingBag',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: -75,
        },
      ],
    },
    {
      id: 4,
      number: 4,
      title: 'Unit 4: Fashion & Celebrations',
      description: 'Discuss clothing styles, holidays, and parties',
      color: 'bg-[#ce82ff]',
      skills: [
        {
          id: 'sk_fashion',
          title: 'Fashion & Style',
          description: 'Compare colors, sizes, and outfits',
          icon: 'ShoppingBag',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 0,
        },
        {
          id: 'sk_celebrations',
          title: 'Celebrations',
          description: 'Birthday wishes, gift giving, and holidays',
          icon: 'Smile',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 50,
        },
        {
          id: 'sk_nature',
          title: 'Nature & Wildlife',
          description: 'Explore beaches, mountains, and wildlife',
          icon: 'Compass',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 80,
        },
        {
          id: 'sk_parties',
          title: 'Parties & Events',
          description: 'Dance, music, and party food',
          icon: 'Utensils',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 80,
        },
        {
          id: 'sk_seasons',
          title: 'Four Seasons',
          description: 'Spring flowers, summer beach, autumn leaves',
          icon: 'Smile',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 50,
        },
        {
          id: 'sk_gifts',
          title: 'Gift Shopping',
          description: 'Wrap gifts and write holiday greeting cards',
          icon: 'ShoppingBag',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: -50,
        },
        {
          id: 'sk_traditions',
          title: 'Family Traditions',
          description: 'Annual family reunions and traditional food',
          icon: 'Users',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: -80,
        },
      ],
    },
    {
      id: 5,
      number: 5,
      title: 'Unit 5: Conversations & Culture',
      description: 'Share opinions, discuss music, and master idioms',
      color: 'bg-[#ff4b4b]',
      skills: [
        {
          id: 'sk_opinions',
          title: 'Opinions & Debates',
          description: 'Agree, disagree, and explain reasoning',
          icon: 'MessageSquare',
          status: 'LOCKED',
          totalLessons: 5,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 0,
        },
        {
          id: 'sk_culture',
          title: 'Spanish Culture',
          description: 'Explore traditions, food customs, and festivals',
          icon: 'UserCheck',
          status: 'LOCKED',
          totalLessons: 5,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 55,
        },
        {
          id: 'sk_music',
          title: 'Music & Arts',
          description: 'Discuss instruments, genres, and concerts',
          icon: 'Smile',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 90,
        },
        {
          id: 'sk_literature',
          title: 'Books & Stories',
          description: 'Read Spanish short stories and novels',
          icon: 'Book',
          status: 'LOCKED',
          totalLessons: 5,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 90,
        },
        {
          id: 'sk_cinema',
          title: 'Movies & TV',
          description: 'Discuss film genres and cinema tickets',
          icon: 'Smile',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 55,
        },
        {
          id: 'sk_idioms',
          title: 'Spanish Idioms',
          description: 'Master colorful proverbs and local slang',
          icon: 'MessageSquare',
          status: 'LOCKED',
          totalLessons: 5,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: -55,
        },
        {
          id: 'sk_fluency',
          title: 'Fluency Mastery',
          description: 'Complex debates and natural conversations',
          icon: 'UserCheck',
          status: 'LOCKED',
          totalLessons: 6,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: -90,
        },
      ],
    },
  ],
};

const LESSON_1_DATA: Lesson = {
  id: 1,
  skillId: '1',
  skillTitle: 'Basic Greetings',
  totalExercises: 8,
  xpReward: 10,
  exercises: [
    {
      id: 1,
      type: 'MULTIPLE_CHOICE',
      question: 'Select the correct translation for "Hello"',
      prompt: 'Select the correct translation for "Hello"',
      options: ['Hola', 'Adiós', 'Gracias', 'Por favor'],
      correctAnswer: 0,
      audioText: 'Hola',
    },
    {
      id: 2,
      type: 'TRANSLATE',
      question: 'Translate this sentence into English',
      prompt: 'Translate this sentence into English',
      originalText: '¡Buenos días! ¿Cómo estás?',
      wordBank: ['Good', 'morning!', 'How', 'are', 'you?', 'Night', 'Thanks', 'Bye'],
      correctAnswer: 'Good morning! How are you?',
      audioText: 'Buenos días. ¿Cómo estás?',
    },
    {
      id: 3,
      type: 'MATCH_PAIRS',
      question: 'Match the corresponding Spanish and English pairs',
      prompt: 'Match the corresponding Spanish and English pairs',
      pairs: [
        { id: 'p1', left: 'Hola', right: 'Hello' },
        { id: 'p2', left: 'Gracias', right: 'Thank you' },
        { id: 'p3', left: 'Por favor', right: 'Please' },
        { id: 'p4', left: 'Adiós', right: 'Goodbye' },
      ],
      correctAnswer: 'matched_all',
    },
    {
      id: 4,
      type: 'FILL_BLANK',
      question: 'Complete the sentence',
      prompt: 'Complete the sentence',
      sentencePrefix: '¡Muchas',
      sentenceSuffix: 'por la ayuda!',
      options: ['gracias', 'hola', 'adiós', 'días'],
      correctAnswer: 'gracias',
      audioText: 'Muchas gracias por la ayuda',
    },
    {
      id: 5,
      type: 'TYPE_ANSWER',
      question: 'Type the Spanish word for "Good night"',
      prompt: 'Type the Spanish word for "Good night"',
      correctAnswer: 'Buenas noches',
      audioText: 'Buenas noches',
    },
    {
      id: 6,
      type: 'TRANSLATE',
      question: 'Translate to Spanish',
      prompt: 'Translate to Spanish',
      originalText: 'Nice to meet you',
      wordBank: ['Mucho', 'gusto', 'en', 'conocerle', 'Hola', 'Gracias'],
      correctAnswer: 'Mucho gusto',
      audioText: 'Mucho gusto',
    },
    {
      id: 7,
      type: 'MULTIPLE_CHOICE',
      question: 'How do you say "Please" in Spanish?',
      prompt: 'How do you say "Please" in Spanish?',
      options: ['Por favor', 'De nada', 'Disculpe', 'Lo siento'],
      correctAnswer: 0,
      audioText: 'Por favor',
    },
    {
      id: 8,
      type: 'FILL_BLANK',
      question: 'Complete the sentence',
      prompt: 'Complete the sentence',
      sentencePrefix: 'Mi nombre',
      sentenceSuffix: 'Orion.',
      options: ['es', 'gracias', 'hola', 'adiós'],
      correctAnswer: 'es',
      audioText: 'Mi nombre es Orion.',
    },
  ],
};

export const MOCK_LESSONS: Record<string, Lesson> = {
  '1': LESSON_1_DATA,
};

export function getMockLesson(id: number | string): Lesson {
  return {
    ...LESSON_1_DATA,
    id: typeof id === 'number' ? id : parseInt(id, 10) || 1,
  };
}

