import { Course } from '@/types/course';
import { Lesson } from '@/types/lesson';
import { UserProfile, Achievement } from '@/types/user';
import { LeaderboardData } from '@/types/leaderboard';

export const MOCK_USER: UserProfile = {
  id: 'usr_101',
  username: 'Alex_Developer',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  streak: 14,
  longestStreak: 21,
  xp: 1250,
  hearts: 5,
  maxHearts: 5,
  gems: 480,
  completedSkills: 6,
  totalSkills: 18,
  dailyGoal: 50,
  dailyGoalProgress: 35,
  league: 'Gold League',
  leagueRank: 4,
  joinedDate: 'October 2024',
};

export const MOCK_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach_1',
    title: 'Wildfire',
    description: 'Reach a 14-day streak',
    icon: '🔥',
    progress: 14,
    maxProgress: 14,
    unlocked: true,
    rewardGems: 50,
  },
  {
    id: 'ach_2',
    title: 'Sage',
    description: 'Earn 2,000 XP',
    icon: '⚡',
    progress: 1250,
    maxProgress: 2000,
    unlocked: false,
    rewardGems: 100,
  },
  {
    id: 'ach_3',
    title: 'Scholar',
    description: 'Learn 50 new words',
    icon: '📚',
    progress: 42,
    maxProgress: 50,
    unlocked: false,
    rewardGems: 75,
  },
  {
    id: 'ach_4',
    title: 'Sharpshooter',
    description: 'Complete 5 lessons with 100% accuracy',
    icon: '🎯',
    progress: 5,
    maxProgress: 5,
    unlocked: true,
    rewardGems: 60,
  },
  {
    id: 'ach_5',
    title: 'Champion',
    description: 'Finish in the Top 3 of your league',
    icon: '🏆',
    progress: 1,
    maxProgress: 1,
    unlocked: true,
    rewardGems: 150,
  },
];

export const MOCK_COURSE: Course = {
  id: 1,
  name: 'Spanish',
  code: 'es',
  flag: '🇪🇸',
  units: [
    {
      id: 1,
      number: 1,
      title: 'Unit 1: Basics & Essentials',
      description: 'Form basic sentences, greet people, and order food',
      color: 'bg-emerald-500',
      skills: [
        {
          id: 'sk_greetings',
          title: 'Greetings',
          description: 'Say hello and ask how people are doing',
          icon: 'MessageSquare',
          status: 'COMPLETED',
          totalLessons: 3,
          completedLessons: 3,
          crowns: 3,
          maxCrowns: 3,
          positionOffset: 0,
        },
        {
          id: 'sk_introductions',
          title: 'Introductions',
          description: 'Introduce yourself and ask names',
          icon: 'UserCheck',
          status: 'COMPLETED',
          totalLessons: 4,
          completedLessons: 4,
          crowns: 3,
          maxCrowns: 3,
          positionOffset: 30,
        },
        {
          id: 'sk_food',
          title: 'Food & Drinks',
          description: 'Order food, coffee, and ask for the bill',
          icon: 'Utensils',
          status: 'CURRENT',
          totalLessons: 4,
          completedLessons: 2,
          crowns: 1,
          maxCrowns: 3,
          positionOffset: 15,
        },
        {
          id: 'sk_family',
          title: 'Family',
          description: 'Talk about your family members and pets',
          icon: 'Users',
          status: 'AVAILABLE',
          totalLessons: 5,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: -25,
        },
        {
          id: 'sk_travel',
          title: 'Travel & Taxi',
          description: 'Ask for directions and buy train tickets',
          icon: 'Compass',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: -40,
        },
      ],
    },
    {
      id: 2,
      number: 2,
      title: 'Unit 2: Daily Life & Routines',
      description: 'Describe daily activities, shopping, and work',
      color: 'bg-sky-500',
      skills: [
        {
          id: 'sk_shopping',
          title: 'Shopping',
          description: 'Ask prices and buy clothes',
          icon: 'ShoppingBag',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: -10,
        },
        {
          id: 'sk_hobbies',
          title: 'Hobbies',
          description: 'Express what sports and activities you like',
          icon: 'Smile',
          status: 'LOCKED',
          totalLessons: 5,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 25,
        },
        {
          id: 'sk_home',
          title: 'My House',
          description: 'Describe furniture and rooms',
          icon: 'Home',
          status: 'LOCKED',
          totalLessons: 4,
          completedLessons: 0,
          crowns: 0,
          maxCrowns: 3,
          positionOffset: 35,
        },
      ],
    },
  ],
};

export const MOCK_LESSONS: Record<string, Lesson> = {
  'sk_food': {
    id: 101,
    skillId: 'sk_food',
    skillTitle: 'Food & Drinks',
    totalExercises: 5,
    xpReward: 15,
    exercises: [
      {
        id: 1,
        type: 'MULTIPLE_CHOICE',
        question: 'Select the correct translation for "Water"',
        prompt: 'Water',
        audioText: 'Agua',
        options: ['El agua', 'El pan', 'El queso', 'La manzana'],
        correctAnswer: 0,
      },
      {
        id: 2,
        type: 'TRANSLATE',
        question: 'Translate this sentence into English',
        originalText: 'Yo quiero un café con leche.',
        audioText: 'Yo quiero un café con leche.',
        wordBank: ['I', 'want', 'a', 'coffee', 'with', 'milk', 'tea', 'please', 'sugar'],
        correctAnswer: 'I want a coffee with milk',
      },
      {
        id: 3,
        type: 'MATCH_PAIRS',
        question: 'Tap the matching pairs',
        pairs: [
          { id: 'p1', left: 'El pan', right: 'The bread' },
          { id: 'p2', left: 'La manzana', right: 'The apple' },
          { id: 'p3', left: 'Gracias', right: 'Thank you' },
          { id: 'p4', left: 'Por favor', right: 'Please' },
        ],
      },
      {
        id: 4,
        type: 'FILL_BLANK',
        question: 'Complete the missing word in the sentence',
        sentencePrefix: 'Una mesa para dos personas, ',
        sentenceSuffix: '.',
        options: ['por favor', 'hasta luego', 'buenos días', 'de nada'],
        correctAnswer: 'por favor',
      },
      {
        id: 5,
        type: 'TYPE_ANSWER',
        question: 'Type the Spanish word for "Goodbye"',
        prompt: 'Goodbye',
        audioText: 'Adiós',
        correctAnswer: 'Adiós',
        acceptableAnswers: ['adios', 'Adiós', 'Adios'],
      },
    ],
  },
  'sk_greetings': {
    id: 102,
    skillId: 'sk_greetings',
    skillTitle: 'Greetings',
    totalExercises: 5,
    xpReward: 15,
    exercises: [
      {
        id: 1,
        type: 'MULTIPLE_CHOICE',
        question: 'How do you say "Hello" in Spanish?',
        prompt: 'Hello',
        audioText: 'Hola',
        options: ['Hola', 'Adiós', 'Gracias', 'Por favor'],
        correctAnswer: 0,
      },
      {
        id: 2,
        type: 'TRANSLATE',
        question: 'Translate into English',
        originalText: 'Buenos días, ¿cómo estás?',
        audioText: 'Buenos días, ¿cómo estás?',
        wordBank: ['Good', 'morning', 'how', 'are', 'you', 'night', 'see', 'later'],
        correctAnswer: 'Good morning how are you',
      },
      {
        id: 3,
        type: 'MATCH_PAIRS',
        question: 'Match the greetings',
        pairs: [
          { id: 'g1', left: 'Hola', right: 'Hello' },
          { id: 'g2', left: 'Buenas noches', right: 'Good night' },
          { id: 'g3', left: 'Hasta luego', right: 'See you later' },
          { id: 'g4', left: 'Mucho gusto', right: 'Nice to meet you' },
        ],
      },
      {
        id: 4,
        type: 'FILL_BLANK',
        question: 'Fill in the blank',
        sentencePrefix: '¡Hola! Me ',
        sentenceSuffix: ' Alex.',
        options: ['llamo', 'soy', 'tengo', 'estoy'],
        correctAnswer: 'llamo',
      },
      {
        id: 5,
        type: 'TYPE_ANSWER',
        question: 'Type the English for "Gracias"',
        prompt: 'Gracias',
        audioText: 'Gracias',
        correctAnswer: 'Thank you',
        acceptableAnswers: ['Thank you', 'thanks', 'Thanks'],
      },
    ],
  },
};

export const MOCK_LEADERBOARD: LeaderboardData = {
  league: 'Gold League',
  timeRemainingDays: 3,
  entries: [
    { rank: 1, id: 'u_1', username: 'Sofia_G', avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80', xp: 1840, isCurrentUser: false, streak: 42 },
    { rank: 2, id: 'u_2', username: 'Liam_Polyglot', avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80', xp: 1560, isCurrentUser: false, streak: 28 },
    { rank: 3, id: 'u_3', username: 'Elena_Ru', avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80', xp: 1390, isCurrentUser: false, streak: 19 },
    { rank: 4, id: 'usr_101', username: 'Alex_Developer', avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80', xp: 1250, isCurrentUser: true, streak: 14 },
    { rank: 5, id: 'u_4', username: 'Mateo_V', avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80', xp: 1120, isCurrentUser: false, streak: 8 },
    { rank: 6, id: 'u_5', username: 'Priya_S', avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80', xp: 980, isCurrentUser: false, streak: 12 },
    { rank: 7, id: 'u_6', username: 'Kenji_Tokyo', avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=80', xp: 850, isCurrentUser: false, streak: 5 },
  ],
};
